### ISSUE TITLE
Implement dropdown within text input

### ISSUE THREAD

**Issue by theViTALiTY** [lanaco/lnc-react-ui#186]
![image](https://user-images.githubusercontent.com/7722017/182550745-695ce24f-f279-4788-a769-d33c3891f1f2.png)
![image](https://user-images.githubusercontent.com/7722017/182550834-9501dc29-90d6-4e39-a283-12793a18d5b1.png)

**Comment by zubacm** [comment]
Added story in Text Input where Dropdown is prefix component.

![image](https://user-images.githubusercontent.com/46137823/191691643-04e649fe-c640-47b6-af9d-fd0c32b2b89a.png)

Should it be made as special component? If so, what kind of input would it be (it has 2 inputs - text input and dropdown select)
