### ISSUE TITLE
Fix dropdown menu component

### ISSUE THREAD

**Issue by vladanracic** [lanaco/lnc-react-ui#281]
- [ ] Add a small light border on the popup
- [ ] Close the popup menu when a menu item is clicked

The menu items don't have the hover effect, is it like that by design ?

![image](https://user-images.githubusercontent.com/85110688/191259042-fc0c20e9-ac35-4035-8a9a-a1cb1744fcf1.png)

**Comment by zubacm** [comment]
Added new prop **closeOnItemSelect** which is true by default
