### ISSUE TITLE
Add missing components

### ISSUE THREAD

**Issue by nemanja-d** [lanaco/lnc-react-ui#74]
Check with existing component libraries for components that are missing here. Organize existing components by categories. For missing components add blank components with just name and simple render.

**Comment by theViTALiTY** [comment]
### Components to remove
- TagSelector

### Components to add
- Component for every type input offers (Basic inputs)
- Radio Button
- Radio Group
- Button Group
- Slider

### Checkbox
Should support indeterminate state.

### CheckBox Lookup
Component should receive the API endpoint and perhaps a mapper function, and handle the search on its own.

### Date input
Picker should support ability to choose both month and year you want to select the date from. Currently switching years is only possible by going through all the months within the year.

### Dropdown
Should be a complete implementation dropdown component, that enables search of the provided list items.

### Dropdown Lookup
Receives API endpoint, a mapper function and handles the search on its own.

### Multiselect
Same logic as dropdown, with ability to select multiple results.

### Multiselect Lookup
Receives API endpoint, a mapper function and handles the search on its own.
