### ISSUE TITLE
Revise theme system

### ISSUE THREAD

**Issue by nemanja-d** [lanaco/lnc-react-ui#76]
Check how theme is implemented in other enterprise grade component libraries and suggest updates for our theme system.

**Comment by zubacm** [comment]
Possible use of react context to implement theme pusage.

**Comment by zubacm** [comment]
Define shadows, expand typography with deined values for caption, subtitles, body text, button text, headers, etc.
Define transitions (easing, duration). Define z-index for components that will need it like modal, tooltip, etc.

**Comment by zubacm** [comment]
Branch added.
